export type ResearchLibraryItem = {
  rank: number;
  type: "Book" | "Periodical" | "Paper" | "Archive" | "Institutional record";
  year: string;
  title: string;
  creator: string;
  institution: string;
  tier: "A" | "B";
  rights: string;
  access: "Research copy" | "Metadata only";
  url: string;
  note: string;
};

// Public-safe bibliographic metadata only. Downloaded originals remain in ignored,
// private CAS storage and do not become public or AI-readable through this list.
export const researchLibrary: ResearchLibraryItem[] = [
  {
    rank: 1,
    type: "Archive",
    year: "1946–1951",
    title: "Historical data for the province of Batangas",
    creator: "Philippine local-history compilation",
    institution: "National Library of the Philippines",
    tier: "A",
    rights: "Metadata only",
    access: "Metadata only",
    url: "https://www.elib.gov.ph/details.php?uid=c62d892e4b1d809c4a4a339d55e3d021",
    note: "Retrospective collection; claims require comparison with the archival holding.",
  },
  {
    rank: 2,
    type: "Book",
    year: "1895",
    title: "Filipinas: pequeños estudios; Batangas y su provincia",
    creator: "Manuel Sastrón",
    institution: "Digitized historical book",
    tier: "A",
    rights: "Public domain scan",
    access: "Research copy",
    url: "https://archive.org/details/filipinaspequeo01sastgoog",
    note: "Contemporary regional context; no relevance is assumed until page review.",
  },
  {
    rank: 3,
    type: "Book",
    year: "1903",
    title: "Official handbook of the Philippines and catalogue of the Philippine exhibit",
    creator: "Philippine Exposition Board",
    institution: "Digitized government publication",
    tier: "A",
    rights: "Public domain scan",
    access: "Research copy",
    url: "https://archive.org/details/officialhandboo00wilsgoog",
    note: "Period catalogue for institutional and material-culture context.",
  },
  {
    rank: 4,
    type: "Periodical",
    year: "1912",
    title: "Philippine Craftsman — digitized issue sequence",
    creator: "Bureau of Education, Philippine Islands",
    institution: "University of Michigan / Internet Archive",
    tier: "A",
    rights: "Public domain scans",
    access: "Research copy",
    url: "https://archive.org/search?query=title%3A%28%22Philippine+craftsman%22%29",
    note: "Twenty-two issues preserved for issue-level craft and industry review.",
  },
  {
    rank: 5,
    type: "Book",
    year: "1926",
    title: "The Collection of Primitive Weapons and Armor of the Philippine Islands in the United States National Museum",
    creator: "Herbert W. Krieger",
    institution: "Smithsonian Institution",
    tier: "A",
    rights: "No Copyright — United States",
    access: "Research copy",
    url: "https://doi.org/10.5479/si.03629236.137.1",
    note: "Museum catalogue; controlled passages stay outside AI and public search.",
  },
  {
    rank: 6,
    type: "Book",
    year: "1994",
    title: "Metalcraft",
    creator: "CCP Encyclopedia of Philippine Art editorial project",
    institution: "Cultural Center of the Philippines / National Library",
    tier: "B",
    rights: "Restricted research copy",
    access: "Research copy",
    url: "https://epa.culturalcenter.gov.ph/project_intro_to_sections/",
    note: "Direct craft context; copyright and controlled-content review required.",
  },
  {
    rank: 7,
    type: "Book",
    year: "2002",
    title: "Batangas: Forged in Fire",
    creator: "Ramon N. Villegas, editor",
    institution: "Philippine eLib catalogue",
    tier: "B",
    rights: "Catalogue metadata",
    access: "Metadata only",
    url: "https://www.elib.gov.ph/details.php?uid=ea527f0ec2a5526682842487a58542a1",
    note: "Regional secondary source; access and chapter-level review remain open tasks.",
  },
  {
    rank: 8,
    type: "Paper",
    year: "2016",
    title: "Ang balisong bilang sagisag-kultura ng Barangay Balisong, Taal, Batangas City",
    creator: "Daniel John Felix G. Galvan",
    institution: "De La Salle University",
    tier: "B",
    rights: "Institutional metadata",
    access: "Metadata only",
    url: "https://animorepository.dlsu.edu.ph/etd_bachelors/2831/",
    note: "Direct research lead; full text is not publicly downloadable.",
  },
  {
    rank: 9,
    type: "Institutional record",
    year: "Collection record",
    title: "Knife, Luzon, late 19th–early 20th century",
    creator: "Unrecorded maker",
    institution: "The Metropolitan Museum of Art",
    tier: "A",
    rights: "Metadata only",
    access: "Metadata only",
    url: "https://www.metmuseum.org/art/collection/search/317185",
    note: "Regional material-appearance context; not identified as a balisong.",
  },
  {
    rank: 10,
    type: "Institutional record",
    year: "Collection lead",
    title: "Musée de la Coutellerie, Thiers",
    creator: "Ville de Thiers",
    institution: "Ministère de la Culture, France",
    tier: "A",
    rights: "Institution metadata",
    access: "Metadata only",
    url: "https://pop.culture.gouv.fr/notice/museo/M0129",
    note: "Institutional contact lead for testing, not confirming, French-origin narratives.",
  },
];
