export type ResearchLane = "Direct lead" | "Regional & craft" | "Historical context" | "Comparative context";
export type ScreeningState = "Page leads found" | "Metadata priority" | "Targeted OCR needed" | "Context only";

export type ResearchLibraryItem = {
  rank: number;
  type: "Book" | "Periodical" | "Paper" | "Archive" | "Institutional record";
  year: string;
  title: string;
  creator: string;
  institution: string;
  tier: "A" | "B";
  rights: string;
  access: "Research copy" | "Metadata only";
  url: string;
  lane: ResearchLane;
  screening: ScreeningState;
  locatedPages?: number;
  note: string;
};

export const literatureScreeningSummary = {
  catalogued: 85,
  privatePdfs: 76,
  textBearingPdfs: 75,
  directTermLeads: 1,
  regionalMaterialLeads: 6,
  curatedForReview: 16,
} as const;

// Public-safe bibliographic metadata and aggregate screening status only.
// The local scanner stores no excerpts or source text. Downloaded originals
// remain private and cannot become evidence without page-level human review.
export const researchLibrary: ResearchLibraryItem[] = [
  {
    rank: 1,
    type: "Book",
    year: "1994",
    title: "Metalcraft",
    creator: "Cultural Center of the Philippines editorial project",
    institution: "Cultural Center of the Philippines / National Library",
    tier: "B",
    rights: "Restricted research copy",
    access: "Research copy",
    url: "https://epa.culturalcenter.gov.ph/project_intro_to_sections/",
    lane: "Direct lead",
    screening: "Page leads found",
    locatedPages: 3,
    note: "The deterministic screen found direct subject-term leads on three pages. Restricted text remains private; a reviewer must inspect and cite it.",
  },
  {
    rank: 2,
    type: "Paper",
    year: "2016",
    title: "Ang balisong bilang sagisag-kultura ng Barangay Balisong, Taal, Batangas City",
    creator: "Daniel John Felix G. Galvan",
    institution: "De La Salle University",
    tier: "B",
    rights: "Institutional metadata",
    access: "Metadata only",
    url: "https://animorepository.dlsu.edu.ph/etd_bachelors/2831/",
    lane: "Direct lead",
    screening: "Metadata priority",
    note: "Direct cultural-research lead. Obtain the full thesis through an authorized institutional channel before claim extraction.",
  },
  {
    rank: 3,
    type: "Archive",
    year: "1946–1951",
    title: "Historical data for the province of Batangas",
    creator: "Philippine local-history compilation",
    institution: "National Library of the Philippines",
    tier: "A",
    rights: "Metadata only",
    access: "Metadata only",
    url: "https://www.elib.gov.ph/details.php?uid=c62d892e4b1d809c4a4a339d55e3d021",
    lane: "Direct lead",
    screening: "Metadata priority",
    note: "High-priority local-history holding. Compare the archival copy with later web transcriptions; do not count them as independent sources.",
  },
  {
    rank: 4,
    type: "Book",
    year: "1895",
    title: "Filipinas: pequeños estudios; Batangas y su provincia",
    creator: "Manuel Sastrón",
    institution: "University of Michigan / Internet Archive",
    tier: "A",
    rights: "Public domain scan",
    access: "Research copy",
    url: "https://archive.org/details/filipinaspequeo01sastgoog",
    lane: "Direct lead",
    screening: "Targeted OCR needed",
    note: "Contemporary regional book prioritized from its title and date. Embedded text produced no reliable term leads, so targeted OCR and Spanish-language review come next.",
  },
  {
    rank: 5,
    type: "Archive",
    year: "1904",
    title: "Official catalogue Philippine exhibits: Universal Exposition, St. Louis",
    creator: "Louisiana Purchase Exposition",
    institution: "Boston Public Library / Internet Archive",
    tier: "A",
    rights: "Public domain scan",
    access: "Research copy",
    url: "https://archive.org/details/officialcatalogu00loui_2",
    lane: "Regional & craft",
    screening: "Page leads found",
    locatedPages: 19,
    note: "Nineteen pages co-locate regional and material-culture terms. These are navigation leads, not accepted evidence.",
  },
  {
    rank: 6,
    type: "Book",
    year: "1906",
    title: "The Philippine Islands",
    creator: "John Foreman",
    institution: "University of California Libraries / Internet Archive",
    tier: "A",
    rights: "Public domain scan",
    access: "Research copy",
    url: "https://archive.org/details/island00forephilippinerich",
    lane: "Regional & craft",
    screening: "Page leads found",
    locatedPages: 4,
    note: "Four pages co-locate regional and material-culture terms. Authorial position and source dependence require explicit review.",
  },
  {
    rank: 7,
    type: "Book",
    year: "1904",
    title: "Souvenir of the Philippine exposition, World's Fair, St Louis",
    creator: "Louisiana Purchase Exposition",
    institution: "Getty Research Institute / Internet Archive",
    tier: "A",
    rights: "Public domain scan",
    access: "Research copy",
    url: "https://archive.org/details/souvenirofphilip00loui",
    lane: "Regional & craft",
    screening: "Page leads found",
    locatedPages: 1,
    note: "One regional/material co-occurrence page was surfaced for human review. Exhibition framing and provenance must be evaluated.",
  },
  {
    rank: 8,
    type: "Periodical",
    year: "1912–1917",
    title: "Philippine Craftsman — digitized issue sequence",
    creator: "Bureau of Education, Philippine Islands",
    institution: "University of Michigan / Internet Archive",
    tier: "A",
    rights: "Public domain scans",
    access: "Research copy",
    url: "https://archive.org/search?query=title%3A%28%22Philippine+craftsman%22%29",
    lane: "Regional & craft",
    screening: "Page leads found",
    locatedPages: 2,
    note: "Twenty-two issues retained for issue-level craft and industry review; results are ranked per issue rather than merged as independent evidence.",
  },
  {
    rank: 9,
    type: "Archive",
    year: "1905",
    title: "Census of the Philippine Islands — four-volume scan set",
    creator: "United States Bureau of the Census / Philippine Commission",
    institution: "University of Michigan and contributing libraries",
    tier: "A",
    rights: "Public domain scans",
    access: "Research copy",
    url: "https://archive.org/details/ajb5834.0004.001.umich.edu",
    lane: "Historical context",
    screening: "Page leads found",
    note: "Regional and industrial context only. It cannot establish a design chronology without a directly relevant reviewed passage.",
  },
  {
    rank: 10,
    type: "Book",
    year: "1913",
    title: "Economic conditions in the Philippines",
    creator: "Hugo Herman Miller and Charles H. Storms",
    institution: "University of Michigan / Internet Archive",
    tier: "A",
    rights: "Public domain scan",
    access: "Research copy",
    url: "https://archive.org/details/afq6770.0001.001.umich.edu",
    lane: "Historical context",
    screening: "Page leads found",
    note: "Useful for regional economic context and terminology. No direct subject term was found in the embedded text.",
  },
  {
    rank: 11,
    type: "Archive",
    year: "1904",
    title: "Report of the Philippine Exposition Board",
    creator: "Philippines Exposition Board",
    institution: "University of California Libraries / Internet Archive",
    tier: "A",
    rights: "Public domain scan",
    access: "Research copy",
    url: "https://archive.org/details/reportofphilippi00philrich",
    lane: "Historical context",
    screening: "Page leads found",
    note: "Official exhibition context. Treat institutional categories and awards as period records, not neutral descriptions.",
  },
  {
    rank: 12,
    type: "Periodical",
    year: "1908–1919",
    title: "The Philippine Journal of Science — ten-volume selection",
    creator: "Philippines Bureau of Science",
    institution: "Smithsonian Libraries and contributing libraries",
    tier: "A",
    rights: "Public domain scans",
    access: "Research copy",
    url: "https://archive.org/search?query=title%3A%28%22The+Philippine+journal+of+science%22%29",
    lane: "Historical context",
    screening: "Context only",
    note: "Retained for period vocabulary and regional context. The first pass found no direct subject term in the selected volumes.",
  },
  {
    rank: 13,
    type: "Book",
    year: "1926",
    title: "The Collection of Primitive Weapons and Armor of the Philippine Islands in the United States National Museum",
    creator: "Herbert W. Krieger",
    institution: "Smithsonian Institution",
    tier: "A",
    rights: "No Copyright — United States",
    access: "Research copy",
    url: "https://doi.org/10.5479/si.03629236.137.1",
    lane: "Comparative context",
    screening: "Page leads found",
    note: "Museum material-culture catalogue. Controlled measurements and technical passages remain excluded from AI and public search.",
  },
  {
    rank: 14,
    type: "Book",
    year: "2002",
    title: "Batangas: Forged in Fire",
    creator: "Ramon N. Villegas, editor",
    institution: "Philippine eLib catalogue",
    tier: "B",
    rights: "Catalogue metadata",
    access: "Metadata only",
    url: "https://www.elib.gov.ph/details.php?uid=ea527f0ec2a5526682842487a58542a1",
    lane: "Historical context",
    screening: "Metadata priority",
    note: "Regional secondary-source lead; access and chapter-level review remain open tasks.",
  },
  {
    rank: 15,
    type: "Institutional record",
    year: "late 19th–early 20th century",
    title: "Knife, Luzon",
    creator: "Unrecorded maker",
    institution: "The Metropolitan Museum of Art",
    tier: "A",
    rights: "Metadata only",
    access: "Metadata only",
    url: "https://www.metmuseum.org/art/collection/search/317185",
    lane: "Comparative context",
    screening: "Context only",
    note: "Regional material-appearance context; the museum record is not identified here as the exhibition subject.",
  },
  {
    rank: 16,
    type: "Institutional record",
    year: "Collection lead",
    title: "Musée de la Coutellerie, Thiers",
    creator: "Ville de Thiers",
    institution: "Ministère de la Culture, France",
    tier: "A",
    rights: "Institution metadata",
    access: "Metadata only",
    url: "https://pop.culture.gouv.fr/notice/museo/M0129",
    lane: "Comparative context",
    screening: "Metadata priority",
    note: "Institutional contact lead for testing, not confirming, recurring French-origin narratives.",
  },
];
