export type ResearchLane = "Direct lead" | "Regional & craft" | "Historical context" | "Comparative context";
export type ScreeningState = "Page leads found" | "Metadata priority" | "Targeted OCR needed" | "Context only";

export type ResearchLibraryItem = {
  rank: number;
  type: "Book" | "Periodical" | "Paper" | "Archive" | "Institutional record";
  year: string;
  yearZh: string;
  title: string;
  titleZh: string;
  creator: string;
  creatorZh: string;
  institution: string;
  institutionZh: string;
  tier: "A" | "B" | "C" | "D";
  rights: string;
  rightsZh: string;
  access: "Research copy" | "Metadata only";
  url: string;
  lane: ResearchLane;
  screening: ScreeningState;
  locatedPages?: number;
  note: string;
  noteZh: string;
};

export const literatureScreeningSummary = {
  catalogued: 97,
  privatePdfs: 81,
  textBearingPdfs: 80,
  directTermLeads: 4,
  regionalMaterialLeads: 7,
  curatedForReview: 30,
} as const;

// Public-safe bibliographic metadata and aggregate screening status only.
// The local scanner stores no excerpts or source text. Downloaded originals
// remain private and cannot become evidence without page-level human review.
export const researchLibrary: ResearchLibraryItem[] = [
  {
    rank: 1,
    type: "Book",
    year: "1994",
    yearZh: "1994",
    title: "Metalcraft",
    titleZh: "金属工艺",
    creator: "Cultural Center of the Philippines editorial project",
    creatorZh: "菲律宾文化中心编辑项目",
    institution: "Cultural Center of the Philippines / National Library",
    institutionZh: "菲律宾文化中心／菲律宾国家图书馆",
    tier: "B",
    rights: "Restricted research copy",
    rightsZh: "受限制研究副本",
    access: "Research copy",
    url: "https://epa.culturalcenter.gov.ph/project_intro_to_sections/",
    lane: "Direct lead",
    screening: "Page leads found",
    locatedPages: 3,
    note: "The deterministic screen found direct subject-term leads on three pages. Restricted text remains private; a reviewer must inspect and cite it.",
    noteZh: "确定性筛选在三页中发现了直接主题术语线索。受限制文本保持私有，必须由审核人员检查并引用。",
  },
  {
    rank: 2,
    type: "Paper",
    year: "2016",
    yearZh: "2016",
    title: "Ang balisong bilang sagisag-kultura ng Barangay Balisong, Taal, Batangas City",
    titleZh: "作为八打雁省塔阿尔 Balisong 村文化象征的 balisong",
    creator: "Daniel John Felix G. Galvan",
    creatorZh: "丹尼尔·约翰·费利克斯·G·加尔万",
    institution: "De La Salle University",
    institutionZh: "德拉萨大学",
    tier: "B",
    rights: "Institutional metadata",
    rightsZh: "机构元数据",
    access: "Metadata only",
    url: "https://animorepository.dlsu.edu.ph/etd_bachelors/2831/",
    lane: "Direct lead",
    screening: "Metadata priority",
    note: "Direct cultural-research lead. Obtain the full thesis through an authorized institutional channel before claim extraction.",
    noteZh: "直接相关的文化研究线索。在提取主张之前，需要通过授权机构渠道取得完整论文。",
  },
  {
    rank: 3,
    type: "Archive",
    year: "1946–1951",
    yearZh: "1946—1951",
    title: "Historical data for the province of Batangas",
    titleZh: "八打雁省历史资料",
    creator: "Philippine local-history compilation",
    creatorZh: "菲律宾地方史编纂项目",
    institution: "National Library of the Philippines",
    institutionZh: "菲律宾国家图书馆",
    tier: "A",
    rights: "Metadata only",
    rightsZh: "仅元数据",
    access: "Metadata only",
    url: "https://www.elib.gov.ph/details.php?uid=c62d892e4b1d809c4a4a339d55e3d021",
    lane: "Direct lead",
    screening: "Metadata priority",
    note: "High-priority local-history holding. Compare the archival copy with later web transcriptions; do not count them as independent sources.",
    noteZh: "高优先级地方史馆藏。需要将档案原件与后来的网络转录进行比对，不能把两者计算为独立来源。",
  },
  {
    rank: 4,
    type: "Book",
    year: "1895",
    yearZh: "1895",
    title: "Filipinas: pequeños estudios; Batangas y su provincia",
    titleZh: "《菲律宾小研究：八打雁及其省份》",
    creator: "Manuel Sastrón",
    creatorZh: "曼努埃尔·萨斯特龙",
    institution: "University of Michigan / Internet Archive",
    institutionZh: "密歇根大学／互联网档案馆",
    tier: "A",
    rights: "Public domain scan",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/details/filipinaspequeo01sastgoog",
    lane: "Direct lead",
    screening: "Targeted OCR needed",
    note: "Contemporary regional book prioritized from its title and date. Embedded text produced no reliable term leads, so targeted OCR and Spanish-language review come next.",
    noteZh: "依据标题和出版时间列为优先审核的同期地区书籍。内嵌文本没有产生可靠术语线索，下一步需要定向 OCR 和西班牙语审核。",
  },
  {
    rank: 5,
    type: "Archive",
    year: "1904",
    yearZh: "1904",
    title: "Official catalogue Philippine exhibits: Universal Exposition, St. Louis",
    titleZh: "圣路易斯世界博览会菲律宾展品官方目录",
    creator: "Louisiana Purchase Exposition",
    creatorZh: "路易斯安那购地博览会",
    institution: "Boston Public Library / Internet Archive",
    institutionZh: "波士顿公共图书馆／互联网档案馆",
    tier: "A",
    rights: "Public domain scan",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/details/officialcatalogu00loui_2",
    lane: "Regional & craft",
    screening: "Page leads found",
    locatedPages: 19,
    note: "Nineteen pages co-locate regional and material-culture terms. These are navigation leads, not accepted evidence.",
    noteZh: "十九页同时出现地区和物质文化术语。这些只是页面导航线索，不是已接受证据。",
  },
  {
    rank: 6,
    type: "Book",
    year: "1906",
    yearZh: "1906",
    title: "The Philippine Islands",
    titleZh: "《菲律宾群岛》",
    creator: "John Foreman",
    creatorZh: "约翰·福尔曼",
    institution: "University of California Libraries / Internet Archive",
    institutionZh: "加利福尼亚大学图书馆／互联网档案馆",
    tier: "A",
    rights: "Public domain scan",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/details/island00forephilippinerich",
    lane: "Regional & craft",
    screening: "Page leads found",
    locatedPages: 4,
    note: "Four pages co-locate regional and material-culture terms. Authorial position and source dependence require explicit review.",
    noteZh: "四页同时出现地区和物质文化术语。作者立场与来源依赖关系需要明确审核。",
  },
  {
    rank: 7,
    type: "Book",
    year: "1904",
    yearZh: "1904",
    title: "Souvenir of the Philippine exposition, World's Fair, St Louis",
    titleZh: "圣路易斯世界博览会菲律宾展览纪念册",
    creator: "Louisiana Purchase Exposition",
    creatorZh: "路易斯安那购地博览会",
    institution: "Getty Research Institute / Internet Archive",
    institutionZh: "盖蒂研究所／互联网档案馆",
    tier: "A",
    rights: "Public domain scan",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/details/souvenirofphilip00loui",
    lane: "Regional & craft",
    screening: "Page leads found",
    locatedPages: 1,
    note: "One regional/material co-occurrence page was surfaced for human review. Exhibition framing and provenance must be evaluated.",
    noteZh: "筛选发现一页地区与物质文化术语共现页面，等待人工审核。展览叙事框架和来源链仍需评估。",
  },
  {
    rank: 8,
    type: "Periodical",
    year: "1912–1917",
    yearZh: "1912—1917",
    title: "Philippine Craftsman — digitized issue sequence",
    titleZh: "《菲律宾工匠》数字化期刊序列",
    creator: "Bureau of Education, Philippine Islands",
    creatorZh: "菲律宾群岛教育局",
    institution: "University of Michigan / Internet Archive",
    institutionZh: "密歇根大学／互联网档案馆",
    tier: "A",
    rights: "Public domain scans",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/search?query=title%3A%28%22Philippine+craftsman%22%29",
    lane: "Regional & craft",
    screening: "Page leads found",
    locatedPages: 2,
    note: "Twenty-two issues retained for issue-level craft and industry review; results are ranked per issue rather than merged as independent evidence.",
    noteZh: "保留二十二期用于逐期工艺与产业审核；筛选结果按期刊单期排序，不会合并为多项独立证据。",
  },
  {
    rank: 9,
    type: "Archive",
    year: "1905",
    yearZh: "1905",
    title: "Census of the Philippine Islands — four-volume scan set",
    titleZh: "《菲律宾群岛人口普查》四卷扫描集",
    creator: "United States Bureau of the Census / Philippine Commission",
    creatorZh: "美国人口普查局／菲律宾委员会",
    institution: "University of Michigan and contributing libraries",
    institutionZh: "密歇根大学及其他贡献图书馆",
    tier: "A",
    rights: "Public domain scans",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/details/ajb5834.0004.001.umich.edu",
    lane: "Historical context",
    screening: "Page leads found",
    note: "Regional and industrial context only. It cannot establish a design chronology without a directly relevant reviewed passage.",
    noteZh: "仅作为地区和产业背景材料。没有直接相关且经过审核的段落时，不能据此建立设计年代序列。",
  },
  {
    rank: 10,
    type: "Book",
    year: "1913",
    yearZh: "1913",
    title: "Economic conditions in the Philippines",
    titleZh: "《菲律宾经济状况》",
    creator: "Hugo Herman Miller and Charles H. Storms",
    creatorZh: "雨果·赫尔曼·米勒、查尔斯·H·斯托姆斯",
    institution: "University of Michigan / Internet Archive",
    institutionZh: "密歇根大学／互联网档案馆",
    tier: "A",
    rights: "Public domain scan",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/details/afq6770.0001.001.umich.edu",
    lane: "Historical context",
    screening: "Page leads found",
    note: "Useful for regional economic context and terminology. No direct subject term was found in the embedded text.",
    noteZh: "可用于地区经济背景和术语研究。内嵌文本中没有发现直接主题术语。",
  },
  {
    rank: 11,
    type: "Archive",
    year: "1904",
    yearZh: "1904",
    title: "Report of the Philippine Exposition Board",
    titleZh: "菲律宾博览会委员会报告",
    creator: "Philippines Exposition Board",
    creatorZh: "菲律宾博览会委员会",
    institution: "University of California Libraries / Internet Archive",
    institutionZh: "加利福尼亚大学图书馆／互联网档案馆",
    tier: "A",
    rights: "Public domain scan",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/details/reportofphilippi00philrich",
    lane: "Historical context",
    screening: "Page leads found",
    note: "Official exhibition context. Treat institutional categories and awards as period records, not neutral descriptions.",
    noteZh: "官方展览背景材料。机构分类与奖项应作为时期记录理解，而不能视为中立描述。",
  },
  {
    rank: 12,
    type: "Periodical",
    year: "1908–1919",
    yearZh: "1908—1919",
    title: "The Philippine Journal of Science — ten-volume selection",
    titleZh: "《菲律宾科学杂志》十卷选集",
    creator: "Philippines Bureau of Science",
    creatorZh: "菲律宾科学局",
    institution: "Smithsonian Libraries and contributing libraries",
    institutionZh: "史密森学会图书馆及其他贡献图书馆",
    tier: "A",
    rights: "Public domain scans",
    rightsZh: "公版扫描件",
    access: "Research copy",
    url: "https://archive.org/search?query=title%3A%28%22The+Philippine+journal+of+science%22%29",
    lane: "Historical context",
    screening: "Context only",
    note: "Retained for period vocabulary and regional context. The first pass found no direct subject term in the selected volumes.",
    noteZh: "保留用于研究时期词汇和地区背景。首轮筛选没有在所选卷册中发现直接主题术语。",
  },
  {
    rank: 13,
    type: "Book",
    year: "1926",
    yearZh: "1926",
    title: "The Collection of Primitive Weapons and Armor of the Philippine Islands in the United States National Museum",
    titleZh: "美国国家博物馆藏菲律宾群岛早期武器与护具目录",
    creator: "Herbert W. Krieger",
    creatorZh: "赫伯特·W·克里格",
    institution: "Smithsonian Institution",
    institutionZh: "史密森学会",
    tier: "A",
    rights: "No Copyright — United States",
    rightsZh: "美国境内无版权限制",
    access: "Research copy",
    url: "https://doi.org/10.5479/si.03629236.137.1",
    lane: "Comparative context",
    screening: "Page leads found",
    note: "Museum material-culture catalogue. Controlled measurements and technical passages remain excluded from AI and public search.",
    noteZh: "博物馆物质文化目录。受控测量信息和技术段落继续排除于 AI 与公共搜索。",
  },
  {
    rank: 14,
    type: "Book",
    year: "2002",
    yearZh: "2002",
    title: "Batangas: Forged in Fire",
    titleZh: "《八打雁：火中锻造》",
    creator: "Ramon N. Villegas, editor",
    creatorZh: "拉蒙·N·比列加斯（编）",
    institution: "Philippine eLib catalogue",
    institutionZh: "菲律宾电子图书馆目录",
    tier: "B",
    rights: "Catalogue metadata",
    rightsZh: "目录元数据",
    access: "Metadata only",
    url: "https://www.elib.gov.ph/details.php?uid=ea527f0ec2a5526682842487a58542a1",
    lane: "Historical context",
    screening: "Metadata priority",
    note: "Regional secondary-source lead; access and chapter-level review remain open tasks.",
    noteZh: "地区二手资料线索；获取全文和逐章审核仍是待办任务。",
  },
  {
    rank: 15,
    type: "Institutional record",
    year: "late 19th–early 20th century",
    yearZh: "19 世纪末至 20 世纪初",
    title: "Knife, Luzon",
    titleZh: "吕宋刀具馆藏记录",
    creator: "Unrecorded maker",
    creatorZh: "作者未记录",
    institution: "The Metropolitan Museum of Art",
    institutionZh: "大都会艺术博物馆",
    tier: "A",
    rights: "Metadata only",
    rightsZh: "仅元数据",
    access: "Metadata only",
    url: "https://www.metmuseum.org/art/collection/search/317185",
    lane: "Comparative context",
    screening: "Context only",
    note: "Regional material-appearance context; the museum record is not identified here as the exhibition subject.",
    noteZh: "地区材料外观背景资料；本项目没有把这条博物馆记录认定为展览主题物件。",
  },
  {
    rank: 16,
    type: "Institutional record",
    year: "Collection lead",
    yearZh: "馆藏联系线索",
    title: "Musée de la Coutellerie, Thiers",
    titleZh: "梯也尔刀具博物馆",
    creator: "Ville de Thiers",
    creatorZh: "梯也尔市政府",
    institution: "Ministère de la Culture, France",
    institutionZh: "法国文化部",
    tier: "A",
    rights: "Institution metadata",
    rightsZh: "机构元数据",
    access: "Metadata only",
    url: "https://pop.culture.gouv.fr/notice/museo/M0129",
    lane: "Comparative context",
    screening: "Metadata priority",
    note: "Institutional contact lead for testing, not confirming, recurring French-origin narratives.",
    noteZh: "用于检验反复出现的法国起源叙述的机构联系线索，并不构成对该叙述的确认。",
  },
  {
    rank: 17,
    type: "Book",
    year: "1771",
    yearZh: "1771",
    title: "L'art du coutelier. Première partie",
    titleZh: "《刀匠技艺·第一部分》",
    creator: "Jean-Jacques Perret",
    creatorZh: "让-雅克·佩雷",
    institution: "Bibliothèque nationale de France / Gallica",
    institutionZh: "法国国家图书馆／Gallica",
    tier: "A",
    rights: "Public-domain bibliographic record",
    rightsZh: "公版书目记录",
    access: "Metadata only",
    url: "https://catalogue.bnf.fr/ark:/12148/cb31085475c.public",
    lane: "Comparative context",
    screening: "Metadata priority",
    note: "The BnF record dates the work to 1771. It is a priority primary record for auditing recurring French-origin narratives, but it does not by itself identify a balisong or establish origin.",
    noteZh: "法国国家图书馆记录将该书定年为 1771 年。它是核查反复出现的法国起源叙述的重要第一手书目记录，但本身既没有完成 balisong 识别，也不能确立起源。",
  },
  {
    rank: 18,
    type: "Paper",
    year: "2024",
    yearZh: "2024",
    title: "Transcending Diversity Through Aesthetics: Reflections on Taman Mini Indonesia Indah and Nayong Pilipino",
    titleZh: "《通过美学超越多样性：印度尼西亚缩影公园与菲律宾村的反思》",
    creator: "Mary Vincelle C. Yasa",
    creatorZh: "玛丽·文塞尔·C·亚萨",
    institution: "University of the Philippines Open University",
    institutionZh: "菲律宾大学开放大学",
    tier: "B",
    rights: "Repository research copy",
    rightsZh: "机构仓储研究副本",
    access: "Research copy",
    url: "https://repository.upou.edu.ph/items/111fb70a-64da-46cb-92e7-8a874e1a6bbc",
    lane: "Historical context",
    screening: "Page leads found",
    locatedPages: 2,
    note: "The deterministic screen found two direct-term pages in a study of national cultural display. They are navigation leads only; page-level review must separate period publications from the thesis author's later analysis.",
    noteZh: "确定性筛选在这项国家文化展示研究中发现两页直接术语线索。它们仅用于导航；逐页审核必须区分时期出版物与论文作者后来的分析。",
  },
  {
    rank: 19,
    type: "Institutional record",
    year: "Undated catalogue record",
    yearZh: "目录未标明日期",
    title: "Balisong — short-film thesis catalogue record",
    titleZh: "《Balisong》短片论文目录记录",
    creator: "Leo Joseph S. Mercado",
    creatorZh: "莱奥·约瑟夫·S·梅尔卡多",
    institution: "University of the Philippines Diliman College of Mass Communication / UP Libraries",
    institutionZh: "菲律宾大学迪利曼大众传播学院／菲律宾大学图书馆",
    tier: "B",
    rights: "Catalogue metadata",
    rightsZh: "目录元数据",
    access: "Metadata only",
    url: "https://tuklas.up.edu.ph/Record/UP-99796217613424750",
    lane: "Direct lead",
    screening: "Metadata priority",
    note: "Institutional media-representation lead. Obtain an authorized viewing copy and create locatable observations before proposing any period visualization.",
    noteZh: "机构媒体呈现研究线索。提出任何时期视觉呈现之前，必须通过授权渠道取得可观看副本并创建可定位的观察。",
  },
  {
    rank: 20,
    type: "Institutional record",
    year: "1955",
    yearZh: "1955",
    title: "Balisong — Sampaguita Pictures archive inventory lead",
    titleZh: "《Balisong》——Sampaguita Pictures 电影档案目录线索",
    creator: "Conrado Conde, director; Sampaguita Pictures",
    creatorZh: "康拉多·孔德（导演）；Sampaguita Pictures",
    institution: "Legacy copy of the Sampaguita Pictures archive list",
    institutionZh: "Sampaguita Pictures 档案清单的旧版网页副本",
    tier: "D",
    rights: "Metadata only",
    rightsZh: "仅元数据",
    access: "Metadata only",
    url: "https://www.geocities.ws/sampaguita_pictures/p3.html",
    lane: "Direct lead",
    screening: "Metadata priority",
    note: "The dated studio-inventory lead establishes a media-history checkpoint, not the visual appearance of an object. No frame is cached or treated as evidence.",
    noteZh: "这条有明确年代的片厂目录线索只能建立媒体史节点，不能证明物件外观。项目没有缓存画面，也没有把电影帧当作证据。",
  },
  {
    rank: 21,
    type: "Paper",
    year: "2015",
    yearZh: "2015",
    title: "Status, Problems and Prospects of Agricultural Cutting Tools Manufacturing and Trading in Selected Areas in Taal, Batangas",
    titleZh: "《八打雁塔阿尔部分地区农用切割工具制造与贸易的状况、问题和前景》",
    creator: "Braham Noe D. Cabanding",
    creatorZh: "布拉汉姆·诺埃·D·卡班丁",
    institution: "University of the Philippines Los Baños",
    institutionZh: "菲律宾大学洛斯巴ñ奥斯分校",
    tier: "B",
    rights: "Institutional metadata; restricted full text",
    rightsZh: "机构元数据；全文访问受限",
    access: "Metadata only",
    url: "https://www.ukdr.uplb.edu.ph/etd-undergrad/12244/",
    lane: "Regional & craft",
    screening: "Metadata priority",
    note: "Regional livelihood and intergenerational craft-transmission lead. Process passages are explicitly excluded from AI, embeddings, and public search.",
    noteZh: "用于研究地区生计与代际工艺传承。涉及工序的段落明确排除于 AI、向量和公共搜索。",
  },
  {
    rank: 22,
    type: "Archive",
    year: "1987",
    yearZh: "1987",
    title: "People of the Philippines v. Rogelio Lasanas, et al.",
    titleZh: "菲律宾人民诉 Rogelio Lasanas 等案",
    creator: "Supreme Court of the Philippines",
    creatorZh: "菲律宾最高法院",
    institution: "Supreme Court of the Philippines / Lawphil",
    institutionZh: "菲律宾最高法院／Lawphil",
    tier: "A",
    rights: "Public legal record",
    rightsZh: "公开法律记录",
    access: "Research copy",
    url: "https://lawphil.net/judjuris/juri1987/jul1987/gr_l-48879_1987.html",
    lane: "Historical context",
    screening: "Page leads found",
    locatedPages: 1,
    note: "Primary evidence for regulation vocabulary in 1987. It contributes no design, construction, or motion evidence.",
    noteZh: "用于支持 1987 年的监管术语背景；不提供设计、结构或运动方面的证据。",
  },
  {
    rank: 23,
    type: "Institutional record",
    year: "2013",
    yearZh: "2013",
    title: "Balisong, the Folding Pocket Knife is Taal's Pride",
    titleZh: "《Balisong：塔阿尔引以为傲的折叠物件》",
    creator: "Municipality of Taal",
    creatorZh: "塔阿尔市政府",
    institution: "Municipal Government of Taal",
    institutionZh: "塔阿尔市政府",
    tier: "C",
    rights: "Metadata only; site images not cached",
    rightsZh: "仅元数据；未缓存网站图片",
    access: "Metadata only",
    url: "https://news.taal.gov.ph/balisong-the-folding-pocket-knife-is-taals-pride/",
    lane: "Regional & craft",
    screening: "Metadata priority",
    note: "Useful for the municipality's public cultural framing, but not independent evidence for origin or design chronology.",
    noteZh: "可用于研究地方政府的公共文化叙事，但不能作为起源或设计年代序列的独立证据。",
  },
  {
    rank: 24,
    type: "Archive",
    year: "1953 record",
    yearZh: "1953 年记录",
    title: "History and Cultural Life of Balisong, Bauan, Batangas — transcription lead",
    titleZh: "《八打雁省包安 Balisong 村的历史与文化生活》——转录线索",
    creator: "Juana T. Magbuhat; later web transcription",
    creatorZh: "Juana T. Magbuhat；后期网页转录",
    institution: "National Library holding / independent transcription",
    institutionZh: "菲律宾国家图书馆馆藏／独立转录",
    tier: "D",
    rights: "Discovery metadata only",
    rightsZh: "仅作为发现型元数据",
    access: "Metadata only",
    url: "https://www.batangashistory.date/2019/08/balisong-bauan-batangas-historical-data_15.html",
    lane: "Historical context",
    screening: "Metadata priority",
    note: "The place-name record concerns Balisong in Bauan, not the Taal craft. Verify the transcription against the National Library image before citation.",
    noteZh: "这条地名记录涉及包安的 Balisong，而不是塔阿尔工艺。正式引用前必须与国家图书馆原始影像核对。",
  },
  {
    rank: 25,
    type: "Archive",
    year: "1953 record",
    yearZh: "1953 年记录",
    title: "Historical Data of Taal, Batangas, Part III — transcription lead",
    titleZh: "《八打雁省塔阿尔历史资料·第三部分》——转录线索",
    creator: "Taal local-history compilation; later web transcription",
    creatorZh: "塔阿尔地方史编纂；后期网页转录",
    institution: "National Library holding / independent transcription",
    institutionZh: "菲律宾国家图书馆馆藏／独立转录",
    tier: "D",
    rights: "Discovery metadata only",
    rightsZh: "仅作为发现型元数据",
    access: "Metadata only",
    url: "https://www.batangashistory.date/2023/06/taal-historical-data-part-3.html",
    lane: "Direct lead",
    screening: "Metadata priority",
    locatedPages: 2,
    note: "The transcription has a paginated History of Balisong Knives section and records the craft as an established local industry in 1953. It is one source-family lead, not independent proof of its origin narrative; the National Library images still require comparison.",
    noteZh: "转录稿包含带页码的“Balisong 刀具史”章节，并记录该工艺在 1953 年已是当地产业。它只是同一来源家族中的一条线索，不能独立证明其中的起源叙述；仍须比对国家图书馆原始影像。",
  },
  {
    rank: 26,
    type: "Archive",
    year: "1880",
    yearZh: "1880",
    title: "Clasp-Knife, US Patent 229,706",
    titleZh: "双柄折叠刀美国专利第 229,706 号",
    creator: "Edmund Jansen",
    creatorZh: "埃德蒙·扬森",
    institution: "United States Patent Office",
    institutionZh: "美国专利局",
    tier: "A",
    rights: "Public-domain patent; technical PDF held privately",
    rightsZh: "公版专利；技术 PDF 私有保存",
    access: "Research copy",
    url: "https://patents.google.com/patent/US229706A/en",
    lane: "Comparative context",
    screening: "Page leads found",
    locatedPages: 2,
    note: "The dated drawing directly documents two handle sections rotating around a central implement. This verifies a comparable external form in Solingen by 1880, not a Philippine origin or transmission route. Mechanical detail remains excluded from AI and public search.",
    noteZh: "有明确日期的图版直接记录了两段刀柄围绕中央部分转动的外部构型。这能确认 1880 年索林根已有可比较形态，但不能证明菲律宾起源或传播路线。机械细节继续排除于 AI 和公共搜索。",
  },
  {
    rank: 27,
    type: "Institutional record",
    year: "1969",
    yearZh: "1969",
    title: "Ang Nayong Pilipino, the Philippine Village",
    titleZh: "《菲律宾村》旅游文化手册",
    creator: "Philippine Tourist and Travel Association; Board of Travel and Tourist Industry",
    creatorZh: "菲律宾旅游协会；旅行与旅游业委员会",
    institution: "Kyoto University CSEAS Library / CiNii Books",
    institutionZh: "京都大学东南亚地域研究研究所图书室／CiNii Books",
    tier: "A",
    rights: "Institutional catalogue metadata",
    rightsZh: "机构目录元数据",
    access: "Metadata only",
    url: "https://ci.nii.ac.jp/ncid/BA59540895",
    lane: "Direct lead",
    screening: "Metadata priority",
    note: "The institutional catalogue confirms the 1969 brochure cited by later scholarship for a Batangas-and-balisong section. The original brochure must be consulted before any quotation or object-form observation is accepted.",
    noteZh: "机构目录确认了这部 1969 年手册；后期学术研究指出其中有“八打雁与 balisong”章节。接受任何引文或物件形态观察前，仍须查阅原始手册。",
  },
  {
    rank: 28,
    type: "Archive",
    year: "1971",
    yearZh: "1971",
    title: "Imported Balisong Knives: Notice of Court Decision Regarding Admissibility",
    titleZh: "《进口 Balisong 刀具：关于准入判决的通知》",
    creator: "United States Bureau of Customs",
    creatorZh: "美国海关局",
    institution: "United States Government Publishing Office",
    institutionZh: "美国政府出版局",
    tier: "A",
    rights: "Public United States government record",
    rightsZh: "美国政府公开记录",
    access: "Research copy",
    url: "https://www.govinfo.gov/content/pkg/FR-1971-05-21/pdf/FR-1971-05-21.pdf",
    lane: "Direct lead",
    screening: "Page leads found",
    locatedPages: 1,
    note: "Federal Register page 9263 proves that United States Customs used the term Balisong and described its broad external folding form in 1971. The notice's phrase about origin is an agency assertion, not provenance proof.",
    noteZh: "《联邦公报》第 9263 页证明美国海关在 1971 年使用了 Balisong 一词，并描述了其宽泛外部折叠形态。通知中的起源表述只是机构断言，并不构成来源链证明。",
  },
  {
    rank: 29,
    type: "Periodical",
    year: "1947",
    yearZh: "1947",
    title: "Limang kaluluwa o isang buhay",
    titleZh: "《五个灵魂或一条生命》",
    creator: "Ilang-Ilang editorial publication",
    creatorZh: "《Ilang-Ilang》编辑出版",
    institution: "University of the Philippines Diliman Main Library",
    institutionZh: "菲律宾大学迪利曼主图书馆",
    tier: "A",
    rights: "Digitized periodical; research access only",
    rightsZh: "数字化期刊；仅供研究访问",
    access: "Research copy",
    url: "https://repository.mainlib.upd.edu.ph/omekas/s/rare-periodicals/media/13521",
    lane: "Direct lead",
    screening: "Page leads found",
    locatedPages: 4,
    note: "The dated October 1947 Philippine fiction record verifies popular-media use of the word balisong. It supports terminology and media history only—not origin, manufacture, or a period object form. Operational passages remain excluded.",
    noteZh: "这份有明确日期的 1947 年 10 月菲律宾文学记录核验了 balisong 一词在通俗媒体中的使用。它只支持术语史与媒体史，不能支持起源、制造或同期物件形态；操作性段落继续排除。",
  },
  {
    rank: 30,
    type: "Periodical",
    year: "1951",
    yearZh: "1951",
    title: "The Community-Centered Schools and the Adult Education Program",
    titleZh: "《社区中心学校与成人教育计划》",
    creator: "Gregorio Lardizabal",
    creatorZh: "格雷戈里奥·拉迪萨瓦尔",
    institution: "The Philippine Educator / University of the Philippines Diliman Main Library",
    institutionZh: "《菲律宾教育者》／菲律宾大学迪利曼主图书馆",
    tier: "A",
    rights: "Digitized periodical; controlled research copy",
    rightsZh: "数字化期刊；受控研究副本",
    access: "Research copy",
    url: "https://repository.mainlib.upd.edu.ph/omekas/files/original/b5009d4f2d293814435954ce8890ebb74d4b7ef0.pdf",
    lane: "Direct lead",
    screening: "Page leads found",
    locatedPages: 1,
    note: "The contemporaneous report based on 1950-1951 provincial visits explicitly records balisong production among Batangas community industries. It verifies an active industry by 1951, not an invention date or visual form; the process sentence remains excluded.",
    noteZh: "这份基于 1950—1951 年省区考察的同期报告，明确把 balisong 生产列入八打雁社区产业。它能核验 1951 年已有活跃产业，不能证明发明年代或视觉形态；工艺句继续排除。",
  },
];
