"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ChevronDown, Pencil, Scale, ShieldCheck, X } from "lucide-react";
import Link from "next/link";
import { StatusPill } from "@/components/StatusPill";
import { apiFetch } from "@/lib/api";

type Evidence = { id: string; short_excerpt: string; page_number: number | null; section_title: string; relation: string; evidence_directness: number; evidence_independence: number; reviewer_verified: boolean; source_title?: string; source_tier?: string; source_quality?: number; source_family?: string; rights_status?: string };
type Claim = { id: string; statement: string; claim_type: string; epistemic_status: string; confidence_score: number; confidence_label: string; proposed_by: string; model_run_id: string | null; evidence: Evidence[] };
const isUuid = (value: string) => /^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(value);
const fixture: Claim = { id: "fixture-claim", statement: "The saved fictional sheet describes two muted surface bands.", claim_type: "visual_feature", epistemic_status: "proposed", confidence_score: .72, confidence_label: "medium", proposed_by: "ai", model_run_id: "mock-run", evidence: [{ id: "fixture-evidence", short_excerpt: "This fictional source documents an abstract museum visualization fixture with two muted surface bands…", page_number: 1, section_title: "block 1", relation: "supports", evidence_directness: .86, evidence_independence: .72, reviewer_verified: false }] };

export function ClaimReviewPanel({ projectId = "demo" }: { projectId?: string }) {
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["claims", projectId], queryFn: () => apiFetch<Claim[]>(`/projects/${projectId}/claims`), enabled: isUuid(projectId) });
  const action = useMutation({ mutationFn: ({ id, verb }: { id: string; verb: string }) => apiFetch(`/claims/${id}/${verb}`, { method: "POST" }), onSuccess: () => client.invalidateQueries({ queryKey: ["claims", projectId] }) });
  const verify = useMutation({ mutationFn: (id: string) => apiFetch(`/claim-evidence/${id}/verify`, { method: "POST" }), onSuccess: () => client.invalidateQueries({ queryKey: ["claims", projectId] }) });
  const claims = query.data ?? (projectId === "demo" ? [fixture] : []);
  return <div className="grid gap-4">{claims.map((claim) => { const evidence = claim.evidence?.[0]; const factors = [["Source quality", Math.round((evidence?.source_quality ?? .5) * 100)], ["Directness", Math.round((evidence?.evidence_directness ?? .5) * 100)], ["Independence", Math.round((evidence?.evidence_independence ?? .5) * 100)], ["Overall", Math.round(claim.confidence_score * 100)]] as const; return <article key={claim.id} className="rounded-2xl border border-ink/10 bg-white/60 p-5 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-3 flex gap-2"><StatusPill>{claim.epistemic_status}</StatusPill><StatusPill>{claim.confidence_label}</StatusPill><StatusPill>{claim.proposed_by}</StatusPill></div><h3 className="max-w-3xl font-display text-2xl leading-tight">{claim.statement}</h3></div><span className="rounded-lg bg-ink/5 px-3 py-2 font-mono text-xs text-quiet">{claim.claim_type}</span></div>
    {evidence ? <blockquote className="my-5 border-l-2 border-ochre bg-paper/70 px-4 py-3 text-sm leading-6">“{evidence.short_excerpt}” <footer className="mt-2 flex flex-wrap items-center gap-2 text-xs text-quiet">{evidence.source_title || "Saved source"} · tier {evidence.source_tier || "—"} · page {evidence.page_number ?? "—"} · {evidence.section_title || "saved location"} · family {evidence.source_family?.slice(0, 8) || "—"}<StatusPill>{evidence.reviewer_verified ? "verified" : "unverified"}</StatusPill></footer></blockquote> : <p className="my-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">No evidence link. Publication and acceptance remain blocked.</p>}
    <details className="group border-y border-ink/10 py-3"><summary className="flex cursor-pointer list-none items-center justify-between text-xs font-bold uppercase tracking-[.12em]">Confidence breakdown <ChevronDown size={15} className="group-open:rotate-180"/></summary><div className="mt-4 grid gap-3 sm:grid-cols-4">{factors.map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between text-[10px]"><span>{label}</span><span>{value}%</span></div><div className="h-1.5 overflow-hidden rounded bg-ink/10"><div className="h-full bg-moss" style={{ width: `${value}%` }}/></div></div>)}</div><p className="mt-3 text-xs text-quiet">Formula: 30% source quality, 25% directness, 20% independence, 15% agreement, 10% temporal proximity. Ranking support only; human judgment remains decisive.</p></details>
    {action.error && <p role="alert" className="mt-3 text-sm text-red-800">{action.error.message}</p>}
    <div className="mt-4 flex flex-wrap gap-2">{evidence && !evidence.reviewer_verified && isUuid(evidence.id) && <button onClick={() => verify.mutate(evidence.id)} className="focus-ring inline-flex items-center gap-2 rounded-full border border-moss/40 px-4 py-2 text-xs font-bold text-moss"><ShieldCheck size={14}/> Verify evidence</button>}<button disabled={!isUuid(claim.id)} onClick={() => action.mutate({ id: claim.id, verb: "accept" })} className="focus-ring inline-flex items-center gap-2 rounded-full bg-moss px-4 py-2 text-xs font-bold text-white disabled:opacity-40"><Check size={14}/> Accept</button><button disabled={!isUuid(claim.id)} onClick={() => action.mutate({ id: claim.id, verb: "reject" })} className="focus-ring inline-flex items-center gap-2 rounded-full border border-red-300 px-4 py-2 text-xs font-bold text-red-800 disabled:opacity-40"><X size={14}/> Reject</button><button disabled={!isUuid(claim.id)} onClick={() => action.mutate({ id: claim.id, verb: "dispute" })} className="focus-ring inline-flex items-center gap-2 rounded-full border border-ochre/40 px-4 py-2 text-xs font-bold text-ochre disabled:opacity-40"><Scale size={14}/> Dispute</button><button className="focus-ring inline-flex items-center gap-2 rounded-full border border-ink/20 px-4 py-2 text-xs font-bold"><Pencil size={14}/> Edit</button><Link href="/admin/audit" className="ml-auto self-center text-xs text-quiet">Audit history</Link></div>
  </article>; })}{!claims.length && <div className="rounded-2xl border border-dashed border-ink/20 p-12 text-center text-sm text-quiet">No claim proposals in this project.</div>}</div>;
}
