"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Archive, Boxes, BriefcaseBusiness, CircleAlert, FileImage, FileText, GitBranch, History, LayoutDashboard, LogOut, Network, ScrollText, SearchCheck, Sparkles } from "lucide-react";

const projectId = "demo";
const links = [
  ["Overview",`/admin/projects/${projectId}`,LayoutDashboard],["Artifacts",`/admin/projects/${projectId}/artifacts`,Archive],["Sources",`/admin/projects/${projectId}/sources`,FileText],["Images",`/admin/projects/${projectId}/images`,FileImage],["Claims",`/admin/projects/${projectId}/claims`,Sparkles],["Contradictions",`/admin/projects/${projectId}/contradictions`,CircleAlert],["Evidence graph",`/admin/projects/${projectId}/evidence-graph`,Network],["Timeline",`/admin/projects/${projectId}/timeline`,History],["Reconstruction",`/admin/projects/${projectId}/reconstruction`,Boxes],["Publication",`/admin/projects/${projectId}/publication`,SearchCheck]
] as const;
export function AdminNav() { const pathname=usePathname(); return <aside className="border-b border-white/10 bg-night text-paper lg:fixed lg:inset-y-0 lg:left-0 lg:w-64 lg:border-b-0 lg:border-r"><div className="flex items-center justify-between border-b border-white/10 p-5"><Link href="/admin" className="flex items-center gap-3 no-underline"><span className="grid h-9 w-9 place-items-center rounded-full bg-paper text-ink"><BriefcaseBusiness size={16}/></span><span><strong className="block font-display text-lg">Balisong Atlas</strong><small className="text-[9px] uppercase tracking-[.14em] text-fog">Research workspace</small></span></Link></div><nav className="scrollbar-thin flex gap-2 overflow-x-auto p-3 lg:block lg:h-[calc(100vh-9rem)] lg:overflow-y-auto" aria-label="Research workspace">{links.map(([label,href,Icon])=>{const active=pathname===href||(href.endsWith("artifacts")&&pathname.startsWith(href+"/"))||(href.endsWith("sources")&&pathname.startsWith(href+"/"));return <Link key={label} href={href} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-sm no-underline transition ${active?"bg-white/12 text-white":"text-fog hover:bg-white/7 hover:text-white"}`}><Icon size={16}/>{label}</Link>})}<div className="my-3 hidden h-px bg-white/10 lg:block"/><Link href="/admin/jobs" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-fog no-underline hover:bg-white/7 hover:text-white"><GitBranch size={16}/> Jobs</Link><Link href="/admin/audit" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-fog no-underline hover:bg-white/7 hover:text-white"><ScrollText size={16}/> Audit</Link></nav><Link href="/login" className="hidden items-center gap-3 border-t border-white/10 p-5 text-sm text-fog no-underline hover:text-white lg:flex"><LogOut size={15}/> Sign out</Link></aside>; }
