"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, BookOpen, Boxes, CircleAlert, Globe2, Quote, ScanSearch } from "lucide-react";
import { MuseumHeader } from "@/components/MuseumHeader";
import { EvidenceLegend } from "@/components/EvidenceLegend";
import { useLanguage } from "@/components/Providers";
import { SafeProxyViewer } from "@/features/reconstruction/SafeProxyViewer";
import { ExhibitTimeline } from "./ExhibitTimeline";

export function ExhibitPage({ demo = false }: { demo?: boolean }) {
  const { locale, messages } = useLanguage();
  const title = demo ? "Balisong Atlas Demo Collection" : "Between Two Handles: A Visual History of the Balisong";
  const titleZh = demo ? "Balisong Atlas 证据流程演示集" : "双柄之间：蝴蝶刀的视觉设计史";
  return <div className="min-h-screen"><MuseumHeader/>
    <main>
      <section className="relative overflow-hidden border-b border-ink/10 paper-grid">
        <div className="absolute right-[-8rem] top-[-13rem] h-[34rem] w-[34rem] rounded-full border-[5rem] border-ochre/10" aria-hidden="true"/>
        <div className="mx-auto grid min-h-[78vh] max-w-[1440px] items-end gap-12 px-5 pb-14 pt-20 lg:grid-cols-[1.35fr_.65fr] lg:px-10 lg:pb-20">
          <div className="relative z-10"><p className="eyebrow">Balisong Atlas · Exhibition 01</p><h1 className="mt-7 max-w-5xl font-display text-[clamp(3.4rem,8vw,8.8rem)] leading-[.84] tracking-[-.055em]">{locale === "zh" ? titleZh : title}</h1><div className="museum-rule mt-9 max-w-3xl"/><p className="mt-7 max-w-2xl text-lg leading-8 text-quiet">{demo ? (locale === "zh" ? "一个完全虚构的测试藏品，用于展示来源、引文、人工审核、争议处理与非功能性视觉代理。" : "A wholly fictional collection demonstrating source preservation, citation, human review, contradiction handling, and a nonfunctional visual proxy.") : (locale === "zh" ? "这是第一期展览的研究中模板。尚未发布任何未经审核的历史结论。" : "This is the research-stage structure for the first exhibition. No unreviewed historical conclusions have been published.")}</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="#evidence" className="focus-ring inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-bold text-paper no-underline">{messages.viewEvidence}<ArrowDown size={16}/></Link><Link href={demo?"/exhibits/balisong-atlas-demo/methodology":"/exhibits/between-two-handles/methodology"} className="focus-ring inline-flex items-center gap-2 rounded-full border border-ink/20 px-5 py-3 text-sm font-bold no-underline">{messages.method}<ArrowRight size={16}/></Link></div>
          </div>
          <aside className="relative z-10 border-l border-ink/20 pl-6 lg:mb-4"><Quote className="mb-5 text-ochre"/><p className="font-display text-3xl leading-tight">{messages.tagline}</p><p className="mt-5 text-sm leading-6 text-quiet">Evidence locations, rights, uncertainty, and human review remain visible beside every published interpretation.</p></aside>
        </div>
      </section>

      {!demo && <section className="mx-auto max-w-[1440px] px-5 py-20 lg:px-10"><div className="rounded-3xl border border-ochre/25 bg-ochre/5 p-8 lg:p-12"><CircleAlert className="text-ochre"/><p className="eyebrow mt-6">Draft / 草稿</p><h2 className="mt-3 font-display text-4xl">Evidence collection is in progress.</h2><p className="mt-4 max-w-3xl leading-7 text-quiet">The project seed creates this exhibition as a draft only. Timeline nodes, artifact interpretations, and reconstruction hypotheses will appear here only after evidence binding and human review.</p></div></section>}

      {demo && <>
      <section id="evidence" className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">Research question</p><h2 className="mt-4 font-display text-5xl leading-[1.05]">How can a visual hypothesis expose the trail that produced it?</h2><p className="mt-6 leading-7 text-quiet">The demo follows a saved fixture from source snapshot to reviewed claims, image observations, design features, uncertainty, and a constrained browser visualization.</p></div><div><EvidenceLegend/><div className="mt-6 grid gap-4 sm:grid-cols-3">{[["03","Reviewed claims"],["03","Visual observations"],["01","Open contradiction"]].map(([number,label])=><div key={label} className="rounded-2xl border border-ink/10 bg-white/45 p-5"><strong className="font-display text-4xl">{number}</strong><span className="mt-2 block text-xs uppercase tracking-[.12em] text-quiet">{label}</span></div>)}</div></div></div></section>

      <section className="border-y border-ink/10 bg-ink text-paper"><div className="mx-auto grid max-w-[1440px] gap-0 lg:grid-cols-2"><div className="border-b border-white/10 p-5 lg:border-b-0 lg:border-r lg:p-10"><div className="relative aspect-[3/2] overflow-hidden rounded-2xl"><Image src="/abstract-study-a.png" alt="Abstract fixture with a muted ochre band on a dark field" fill className="object-cover" sizes="(max-width:1024px) 100vw, 50vw"/></div><p className="mt-4 text-xs text-fog">Fictional source fixture A · public domain · complete attribution</p></div><div className="p-5 lg:p-10"><div className="relative aspect-[3/2] overflow-hidden rounded-2xl"><Image src="/abstract-study-b.png" alt="Abstract fixture with alternating circular color fields" fill className="object-cover" sizes="(max-width:1024px) 100vw, 50vw"/></div><p className="mt-4 text-xs text-fog">Fictional source fixture B · public domain · complete attribution</p></div></div></section>

      <section className="mx-auto grid max-w-[1440px] gap-14 px-5 py-24 lg:grid-cols-[.55fr_1.45fr] lg:px-10"><div><p className="eyebrow">Evidence-bound sequence</p><h2 className="mt-4 font-display text-5xl">A timeline of review, not an automatic history.</h2><p className="mt-5 leading-7 text-quiet">Each node names its evidence location, confidence, and uncertainty. Proposed AI summaries never become public timeline entries.</p></div><ExhibitTimeline/></section>

      <section className="bg-parchment/70"><div className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><div className="mb-10 flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Design feature matrix</p><h2 className="mt-4 font-display text-5xl">Visible form, interpreted carefully.</h2></div><Link href="/exhibits/balisong-atlas-demo/artifacts/fictional-kinetic-folding-artifact-a-01" className="inline-flex items-center gap-2 text-sm font-bold">Open artifact record <ArrowRight size={15}/></Link></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[
        ["Silhouette","Rounded continuous contour","Observed"],["Color appearance","Muted two-tone surface","Observed"],["Surface motif","Alternating circular fields","Observed"],["External form","Neutral central field","Inferred"]
      ].map(([category,label,state])=><article key={label} className="rounded-2xl border border-ink/10 bg-paper p-5"><span className="text-[10px] font-bold uppercase tracking-[.13em] text-quiet">{category}</span><h3 className="mt-4 font-display text-2xl">{label}</h3><span className={`mt-8 inline-block rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[.12em] ${state==="Observed"?"bg-moss/10 text-moss":"bg-ochre/10 text-ochre"}`}>{state}</span></article>)}</div></div></section>

      <section className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><div className="mb-10 grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Reconstruction hypothesis</p><h2 className="mt-4 font-display text-5xl">A safe visual proxy with its evidence attached.</h2></div><p className="self-end leading-7 text-quiet">The central element is neutral and abstract. The fixture uses one unitless joined mesh, no internal structure, no moving parts, and no real-world scale. Viewer controls are limited to inspecting the whole scene and its evidence labels.</p></div><SafeProxyViewer/><div className="mt-5 rounded-2xl border border-ochre/20 bg-ochre/5 p-5 text-sm leading-6"><strong>Interpretive reconstruction notice.</strong> This reconstruction is a nonfunctional, evidence-based visual hypothesis. It is not a manufacturing model or an exact historical replica.<br/><span className="text-quiet">本重建是一个非功能性、以证据为基础的视觉假设，不是制造模型，也不是被宣称为完全准确的历史复制品。</span></div></section>

      <section className="border-y border-ink/10"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-2"><div className="border-b border-ink/10 p-8 lg:border-b-0 lg:border-r lg:p-14"><CircleAlert className="text-red-700"/><p className="eyebrow mt-7">Dispute retained</p><h2 className="mt-3 font-display text-4xl">One caption challenges the attribution of a surface band.</h2><p className="mt-5 leading-7 text-quiet">The system does not ask AI to resolve the disagreement. It exposes the source family, evidence relation, and need for expert review.</p></div><div className="p-8 lg:p-14"><Globe2 className="text-moss"/><p className="eyebrow mt-7">Geography & culture</p><h2 className="mt-3 font-display text-4xl">No real-world association is assigned to this fixture.</h2><p className="mt-5 leading-7 text-quiet">This empty state demonstrates that absent geographic evidence is represented as unknown rather than completed from model memory.</p></div></div></section>
      </>}

      <section className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><div className="grid gap-5 md:grid-cols-3">{[
        {icon:ScanSearch,title:"Evidence-first",text:"Claims point to saved snapshots, pages, blocks, regions, and rights records."},
        {icon:BookOpen,title:"Human review",text:"AI proposes. Researchers accept, revise, reject, or preserve disputes."},
        {icon:Boxes,title:"Constrained reconstruction",text:"Only approved visual fields can reach a nonfunctional, unitless public proxy."},
      ].map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-ink/10 p-6"><Icon className="text-ochre"/><h3 className="mt-8 font-display text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-quiet">{text}</p></article>)}</div></section>
    </main>
    <footer className="bg-ink text-paper"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 py-14 lg:grid-cols-2 lg:px-10"><div><strong className="font-display text-3xl">Balisong Atlas</strong><p className="mt-3 max-w-lg text-sm leading-6 text-fog">Evidence-first cultural history, design research, and transparent AI-assisted visual interpretation.</p></div><div className="grid grid-cols-2 gap-5 text-sm"><div><p className="eyebrow !text-fog">Rights</p><p className="mt-3 text-fog">Code: MIT. Data, imagery, and exhibition content retain separate rights statements.</p></div><div><p className="eyebrow !text-fog">AI use</p><p className="mt-3 text-fog">AI output is proposed, validated, audited, and never treated as a historical source.</p></div></div></div></footer>
  </div>;
}
